import sqlite3


from queries import (DROP_MOVIE_TABLE, DROP_PROJECTIONS_TABLE, DROP_USERS_TABLE, DROP_RESERVATIONS_TABLE, CREATE_USER_TABLE, CREATE_MOVIE_TABLE, CREATE_PROJECTIONS_TABLE, CREATE_RESERVATION_TABLE, INSERT_INTO_MOVIES, INSERT_INTO_PROJECTIONS, INSET_INTO_RESERVATIONS)
                     # INSERT_INTO_PROJECTIONS, INSET_INTO_RESERVATIONS)

from connector import Connector


class DBConnector:
    def __init__(self):
        self.connector = Connector()

    def create(self):
        tables = [DROP_MOVIE_TABLE, DROP_PROJECTIONS_TABLE, DROP_USERS_TABLE, DROP_RESERVATIONS_TABLE, CREATE_USER_TABLE, CREATE_MOVIE_TABLE, CREATE_PROJECTIONS_TABLE, CREATE_RESERVATION_TABLE, INSERT_INTO_MOVIES, INSERT_INTO_PROJECTIONS, INSET_INTO_RESERVATIONS]

        for table in tables:
            self.connector.execute(table)





